base_lr: 0.01
batch_size: 256
config: ./config/campus/test_joint2.yaml
device: cpu
eval_interval: 1
feeder: feeders.feeder.Feeder
ignore_weights: []
log_interval: 100
model: model.agcn.Model
model_args:
  graph: graph.campus.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 8
  num_person: 4
  num_point: 17
model_saved_name: ./runs/ca_agcn_test_joint2
nesterov: false
num_epoch: 80
num_worker: 1
only_train_epoch: 0
only_train_part: false
optimizer: SGD
phase: test
print_log: true
save_interval: 10
save_score: true
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 5
- 10
- 15
test_batch_size: 2
test_feeder_args:
  data_path: ./data/campus/val_data_joint2.npy
  debug: false
  label_path: ./data/campus/val_label2.pkl
train_feeder_args: {}
warm_up_epoch: 0
weight_decay: 0.0005
weights: ./runs/ca_agcn_joint2-19-17320.pt
work_dir: ./work_dir/campus/agcn_test_joint2
