base_lr: 0.1
batch_size: 2
config: ./config/campus/train_bone2.yaml
device: cpu
eval_interval: 1
feeder: feeders.feeder.Feeder
ignore_weights: []
log_interval: 100
model: model.agcn.Model
model_args:
  graph: graph.campus.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 8
  num_person: 4
  num_point: 17
model_saved_name: ./runs/ca_agcn_bone2
nesterov: true
num_epoch: 20
num_worker: 1
only_train_epoch: 0
only_train_part: false
optimizer: SGD
phase: train
print_log: true
save_interval: 10
save_score: false
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 4
- 8
- 12
- 16
- 18
- 20
test_batch_size: 2
test_feeder_args:
  data_path: ./data/campus/val_data_bone2.npy
  label_path: ./data/campus/val_label2.pkl
train_feeder_args:
  data_path: ./data/campus/train_data_bone2.npy
  debug: false
  label_path: ./data/campus/train_label2.pkl
  normalization: false
  random_choose: false
  random_move: false
  random_shift: true
  window_size: -1
warm_up_epoch: 0
weight_decay: 0.0001
weights: null
work_dir: ./work_dir/campus/agcn_bone2
