work_dir: ./work_dir/campus/agcn_joint2
model_saved_name: ./runs/ca_agcn_joint2
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/campus/train_data_joint2.npy
  label_path: ./data/campus/train_label2.pkl
  debug: False
  random_choose: False
  random_shift: True
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/campus/val_data_joint2.npy
  label_path: ./data/campus/val_label2.pkl

# model
model: model.aagcn.Model
model_args:
  num_class: 8
  num_point: 17
  num_person: 4
  graph: graph.campus.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [4, 8, 12, 16, 18, 20]

# training
device: 'cpu'
batch_size: 2
test_batch_size: 2
num_epoch: 200
nesterov: True
