work_dir: ./work_dir/campus/agcn_bone
model_saved_name: ./runs/ca_agcn_bone
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/campus/train_data_bone.npy
  label_path: ./data/campus/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/campus/val_data_bone.npy
  label_path: ./data/campus/val_label.pkl

# model
model: model.aagcn.Model
model_args:
  num_class: 4
  num_point: 17
  num_person: 4
  graph: graph.campus.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [4, 8, 9]

# training
device: 'cpu'
batch_size: 2
test_batch_size: 2
num_epoch: 100
nesterov: True

